In [1]:
%matplotlib qt

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


EEGsignal = pd.read_csv('5_1.tdt', sep = '\t')

In [65]:
EEGsignal['O2-AVE'].plot()
plt.show()

In [3]:
from scipy import stats

zscore = np.abs(stats.zscore(EEGsignal))

In [4]:
zscore

array([[3.17899489e-04, 9.56486958e-04, 5.58508816e-04, ...,
        1.92042531e-04, 3.90504101e-04, 5.10923144e-04],
       [5.04602148e-03, 3.93355040e-03, 1.37416734e-03, ...,
        8.25044705e-03, 3.65411902e-03, 5.63817712e-03],
       [3.54183231e-02, 2.51178270e-02, 1.10715938e-02, ...,
        5.76144842e-02, 2.51067824e-02, 3.70790228e-02],
       ...,
       [6.76610939e-01, 6.51764819e-01, 7.04263833e-01, ...,
        5.36125118e-01, 9.87474155e-01, 5.71927374e-01],
       [5.80699247e-01, 5.61996107e-01, 5.50305265e-01, ...,
        2.98614146e-01, 9.04281334e-01, 6.90500445e-01],
       [5.36382207e-01, 4.12373267e-01, 4.16955306e-01, ...,
        1.59654844e-02, 7.58912117e-01, 7.07132740e-01]])

In [5]:
EEGsignal_cleaned = EEGsignal[(zscore < 3).all(axis=1)]

In [42]:
EEGsignal

,FP1-AVE,FP2-AVE,F3-AVE,F4-AVE,C3-AVE,C4-AVE,P3-AVE,P4-AVE,O1-AVE,O2-AVE,F7-AVE,F8-AVE,T3-AVE,T4-AVE,T5-AVE,T6-AVE,Fz-AVE,Cz-AVE,Pz-AVE
0,0.000000,0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000,-0.000000,0.000000,0.000000,-0.000000,0.000000,-0.000000,-0.000000,0.000000,0.000000,-0.000000
1,0.033760,0.020392,-0.013170,0.042574,-0.065139,-0.015834,0.050228,-0.037272,0.022868,0.080835,-0.051392,-0.012768,-0.067817,-0.011816,0.014627,0.022676,0.066893,-0.024733,-0.054912
2,0.250626,0.165498,-0.079252,0.288474,-0.484097,-0.151652,0.349213,-0.295561,0.244327,0.627766,-0.374609,-0.120452,-0.494139,-0.099977,0.116563,0.159554,0.476665,-0.187310,-0.391638
3,0.839319,0.631318,-0.187216,0.864743,-1.637460,-0.674957,1.077871,-1.092498,1.195652,2.237212,-1.224636,-0.504243,-1.636522,-0.408991,0.431627,0.464762,1.502734,-0.642279,-1.236440
4,1.667625,1.504604,-0.173452,1.503274,-3.359195,-1.881725,1.941490,-2.525722,3.636211,4.908042,-2.371869,-1.243336,-3.303697,-1.112679,1.006983,0.619786,2.711648,-1.308458,-2.219533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16564,-6.662706,-4.494320,-7.253375,-3.422197,-9.333989,-4.161500,-3.728463,2.505536,20.369928,29.397354,-6.654185,-0.450905,-4.003706,0.079066,-0.464180,10.776360,-6.329122,-5.965889,-0.203701
16565,-5.851017,-4.599483,-6.059617,-3.500802,-8.156602,-5.703773,-3.293391,-0.771059,18.333860,27.977976,-5.466195,0.074070,-0.393541,-0.050643,1.298563,12.810404,-5.768032,-7.266098,-3.614621
16566,-4.833445,-4.470947,-4.802931,-4.152055,-6.902652,-6.414976,-2.163245,-3.170910,15.921567,26.831734,-4.853817,0.488236,0.830944,-0.466303,2.370281,13.840785,-4.451981,-7.480521,-6.119771
16567,-4.148611,-3.856058,-3.753798,-4.243930,-5.415472,-6.445921,-0.322112,-4.621101,12.808357,23.866287,-4.465345,1.026725,0.590151,-0.756542,3.053203,13.404279,-2.480397,-6.850052,-7.389668
16568,-3.832176,-2.831186,-2.845100,-2.806881,-3.459513,-6.123834,2.221299,-5.378993,8.415253,17.278095,-4.029249,2.070968,0.582129,-0.465724,3.516366,11.138851,-0.134124,-5.748385,-7.567797

In [7]:
EEGsignal_cleaned = EEGsignal_cleaned[['FP1-AVE', 'FP2-AVE', 'F3-AVE', 'F4-AVE', 'F7-AVE', 'F8-AVE', 'Fz-AVE', 'C3-AVE', 'C4-AVE', 'Cz-AVE', 'T3-AVE', 'T4-AVE', 'T5-AVE', 'T6-AVE', 'P3-AVE', 'P4-AVE', 'Pz-AVE', 'O1-AVE', 'O2-AVE']]

In [8]:
EEGsignal_cleaned

,FP1-AVE,FP2-AVE,F3-AVE,F4-AVE,F7-AVE,F8-AVE,Fz-AVE,C3-AVE,C4-AVE,Cz-AVE,T3-AVE,T4-AVE,T5-AVE,T6-AVE,P3-AVE,P4-AVE,Pz-AVE,O1-AVE,O2-AVE
0,0.000000,0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000,0.000000,-0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000,-0.000000
1,0.033760,0.020392,-0.013170,0.042574,-0.051392,-0.012768,0.066893,-0.065139,-0.015834,-0.024733,-0.067817,-0.011816,0.014627,0.022676,0.050228,-0.037272,-0.054912,0.022868,0.080835
2,0.250626,0.165498,-0.079252,0.288474,-0.374609,-0.120452,0.476665,-0.484097,-0.151652,-0.187310,-0.494139,-0.099977,0.116563,0.159554,0.349213,-0.295561,-0.391638,0.244327,0.627766
3,0.839319,0.631318,-0.187216,0.864743,-1.224636,-0.504243,1.502734,-1.637460,-0.674957,-0.642279,-1.636522,-0.408991,0.431627,0.464762,1.077871,-1.092498,-1.236440,1.195652,2.237212
4,1.667625,1.504604,-0.173452,1.503274,-2.371869,-1.243336,2.711648,-3.359195,-1.881725,-1.308458,-3.303697,-1.112679,1.006983,0.619786,1.941490,-2.525722,-2.219533,3.636211,4.908042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16564,-6.662706,-4.494320,-7.253375,-3.422197,-6.654185,-0.450905,-6.329122,-9.333989,-4.161500,-5.965889,-4.003706,0.079066,-0.464180,10.776360,-3.728463,2.505536,-0.203701,20.369928,29.397354
16565,-5.851017,-4.599483,-6.059617,-3.500802,-5.466195,0.074070,-5.768032,-8.156602,-5.703773,-7.266098,-0.393541,-0.050643,1.298563,12.810404,-3.293391,-0.771059,-3.614621,18.333860,27.977976
16566,-4.833445,-4.470947,-4.802931,-4.152055,-4.853817,0.488236,-4.451981,-6.902652,-6.414976,-7.480521,0.830944,-0.466303,2.370281,13.840785,-2.163245,-3.170910,-6.119771,15.921567,26.831734
16567,-4.148611,-3.856058,-3.753798,-4.243930,-4.465345,1.026725,-2.480397,-5.415472,-6.445921,-6.850052,0.590151,-0.756542,3.053203,13.404279,-0.322112,-4.621101,-7.389668,12.808357,23.866287
16568,-3.832176,-2.831186,-2.845100,-2.806881,-4.029249,2.070968,-0.134124,-3.459513,-6.123834,-5.748385,0.582129,-0.465724,3.516366,11.138851,2.221299,-5.378993,-7.567797,8.415253,17.278095

In [99]:
EEGsignal_cleaned.plot(subplots = True)
plt.show()

In [26]:
EEGsignal_cleaned['O2-AVE'].plot()
plt.show()

In [9]:
EEGsignal_cleaned.drop(EEGsignal_cleaned.tail(21).index, inplace =True)

In [10]:
EEGsignal_cleaned_stacked = pd.melt(EEGsignal_cleaned)

In [11]:
EEGsignal_cleaned_stacked

       variable      value
0       FP1-AVE   0.000000
1       FP1-AVE   0.033760
2       FP1-AVE   0.250626
3       FP1-AVE   0.839319
4       FP1-AVE   1.667625
...         ...        ...
296395   O2-AVE  25.142361
296396   O2-AVE  19.643417
296397   O2-AVE  13.450405
296398   O2-AVE   7.403413
296399   O2-AVE   2.315274

[296400 rows x 2 columns]

In [12]:
EEGsignal_cleaned_stacked['variable'] = EEGsignal_cleaned_stacked['variable'].replace(['FP1-AVE', 'FP2-AVE', 'F3-AVE', 'F4-AVE','F7-AVE', 'F8-AVE','Fz-AVE'], 0)
EEGsignal_cleaned_stacked['variable'] = EEGsignal_cleaned_stacked['variable'].replace(['C3-AVE', 'C4-AVE','Cz-AVE'], 1)
EEGsignal_cleaned_stacked['variable'] = EEGsignal_cleaned_stacked['variable'].replace(['T3-AVE', 'T4-AVE', 'T5-AVE', 'T6-AVE'], 2)
EEGsignal_cleaned_stacked['variable'] = EEGsignal_cleaned_stacked['variable'].replace(['P3-AVE', 'P4-AVE', 'O1-AVE', 'O2-AVE', 'Pz-AVE'], 3)

In [13]:
EEGsignal_cleaned_stacked

        variable      value
0              0   0.000000
1              0   0.033760
2              0   0.250626
3              0   0.839319
4              0   1.667625
...          ...        ...
296395         3  25.142361
296396         3  19.643417
296397         3  13.450405
296398         3   7.403413
296399         3   2.315274

[296400 rows x 2 columns]

In [115]:
EEGsignal_cleaned_stacked.plot()
plt.show()

In [14]:
print(EEGsignal_cleaned_stacked)

        variable      value
0              0   0.000000
1              0   0.033760
2              0   0.250626
3              0   0.839319
4              0   1.667625
...          ...        ...
296395         3  25.142361
296396         3  19.643417
296397         3  13.450405
296398         3   7.403413
296399         3   2.315274

[296400 rows x 2 columns]

In [15]:
EEGsignal_cleaned_stacked.to_csv('EEGsignal_cleaned_stacked.csv')

In [16]:
EEGsignal_cleaned_stacked = pd.read_csv('EEGsignal_cleaned_stacked.csv', index_col = 0)

In [17]:
EEGsignal_cleaned_stacked

        variable      value
0              0   0.000000
1              0   0.033760
2              0   0.250626
3              0   0.839319
4              0   1.667625
...          ...        ...
296395         3  25.142361
296396         3  19.643417
296397         3  13.450405
296398         3   7.403413
296399         3   2.315274

[296400 rows x 2 columns]

In [18]:
X = EEGsignal_cleaned_stacked.iloc[:,1]
X = X.to_numpy()
Y = EEGsignal_cleaned_stacked.iloc[:,0]
Y = Y.to_numpy()

In [19]:
Y

array([0, 0, 0, ..., 3, 3, 3], dtype=int64)

In [20]:
X = X.reshape(-1,200)

In [21]:
print(X)

[[  0.         0.03376    0.250626 ...  -8.942858  -7.159401  -4.732432]
 [ -2.360686  -0.615868   0.392653 ...  -0.178296   0.639855   1.675786]
 [  2.719097   3.46789    3.734977 ...  -5.613938  -5.393591  -5.316814]
 ...
 [  6.585794   7.689007   9.279674 ...  -2.318905  -7.148781  -9.468482]
 [-11.014017 -14.789101 -20.79838  ...  14.271112  12.157595   8.788906]
 [  4.763934   0.516968  -4.063508 ...  13.450405   7.403413   2.315274]]

In [22]:
X.shape

(1482, 200)

In [23]:
n0 = np.full((546,),0)
n1 = np.full((234,),1)
n2 = np.full((312,),2)
n3 = np.full((390,),3)

In [24]:
Y = np.concatenate([n0, n1, n2, n3])

In [25]:
print(X.shape)
print(Y.shape)

(1482, 200)
(1482,)

In [26]:
training_data = []
for x, y in zip(X, Y):
    training_data.append([x,y])

In [27]:
print(training_data)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [28]:
print(len(training_data))

1482

In [29]:
import random
random.shuffle(training_data)

In [30]:
for sample in training_data[:30]:
    print(sample[1])

3
3
2
1
0
1
1
1
0
1
0
3
1
3
2
2
3
2
0
1
0
1
2
0
2
3
0
3
3
3

In [31]:
X = []
Y= []

In [32]:
for features, label in training_data:
    X.append(features)
    Y.append(label)

In [33]:
X = np.array(X).reshape(-1, 200, 1)

In [34]:
X.shape

(1482, 200, 1)

In [35]:
import pickle

pickle_out = open("X.pickle","wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("Y.pickle","wb")
pickle.dump(Y, pickle_out)
pickle_out.close()

In [35]:
pickle_in = open("X.pickle","rb")
X = pickle.load(pickle_in)
pickle_in = open("Y.pickle","rb")
Y = pickle.load(pickle_in)

In [36]:
X

array([[[ -3.107831],
        [ -4.180162],
        [ -4.565814],
        ...,
        [-11.373183],
        [ -9.16566 ],
        [ -6.750636]],

       [[ -0.493929],
        [ -4.83234 ],
        [ -9.864531],
        ...,
        [ -4.56712 ],
        [ -7.864475],
        [-10.987309]],

       [[-12.003628],
        [-14.758103],
        [-17.402451],
        ...,
        [ -2.377375],
        [ -2.791151],
        [ -3.24141 ]],

       ...,

       [[  3.090136],
        [  8.440527],
        [ 11.600297],
        ...,
        [ -4.243158],
        [ -3.448584],
        [ -2.907869]],

       [[-12.083249],
        [-13.309189],
        [-13.457642],
        ...,
        [ -4.683374],
        [ -6.148955],
        [ -7.207771]],

       [[-11.653975],
        [-11.414006],
        [-10.477757],
        ...,
        [  4.704395],
        [  1.956568],
        [ -1.398811]]])

In [99]:
print(X.shape[1:])

(200, 1)

numpy.ndarray